### ISSUE TITLE
Migration documentation incomplete

### ISSUE THREAD

**Issue by sandman21dan** [Netflix/metaflow-service#130]
I've just gone through the process of updating the metadata service I've been running and performing the DB migration

I noted some things are missing from the docs (found out going through the python code)

- There's no mention of the environment variable `MF_MIGRATION_ENDPOINTS_ENABLED` which can be used to disable the migration endpoints
- To perform a migration upgrade the needed request is a `PATCH` to `/upgrade` and not `GET` which is not mentioned in the documentation
- The documentation mentions the availability of `python3 migration_tools.py db-status` but actually this `migration_tools.py` script is not bundled in the public docker image from docker hub

Managed to solve these issues myself but I had to spend quite some time inspecting the image and the migration service code. Updating the documentation would help people have an easier time performing their migrations

**Comment by savingoyal** [comment]
Thanks for highlighting the issues. I will update the documentation shortly.

**Comment by adil-bouchaara** [comment]
@savingoyal  please do it as soon as possible,i have been on the same issue for hours, and the upgrade db command is not working, this is from fargate task
```
container_linux.go:380: starting container process caused: exec: "python migration_tools.py upgrade": executable file not found in $PATH
```

**Comment by savingoyal** [comment]
@adil-bouchaara sorry for the delay, we can help you out as chat.metaflow.org meanwhile.
