### ISSUE TITLE
Metadata DB Password should be quoted

### ISSUE THREAD

**Issue by displacedaussie** [Netflix/metaflow-service#152]
When launching a Metaflow stack using the recommended [CloudFormation template](https://github.com/Netflix/metaflow-tools/blob/master/aws/cloudformation/metaflow-cfn-template.yml#L541), an RDS database password is created using AWS Secrets Manager. This is currently configured to exclude the characters `"@/\`.

Unfortunately, this still allows potentially problematic characters like `#` and `'` to be included in the password.

If `'` is included as the _first_ character in the password, the Metadata Service fails to start as follows:

```
/migration_service/migration_server.py:17: DeprecationWarning: loop argument is deprecated
  app = web.Application(loop=loop)
printing connection exception: invalid dsn: unterminated quoted string in connection info string

printing connection exception: invalid dsn: unterminated quoted string in connection info string

printing connection exception: invalid dsn: unterminated quoted string in connection info string

/migration_service/migration_server.py:28: DeprecationWarning: Application.make_handler(...) is deprecated, use AppRunner API instead
  handler = the_app.make_handler()
serving on ('0.0.0.0', 8082)
Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/local/lib/python3.7/dist-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/migration_service/api/admin.py", line 53, in version
    version = await ApiUtils.get_latest_compatible_version()
  File "/migration_service/api/utils.py", line 56, in get_latest_compatible_version
    is_present = await PostgresUtils.is_present("flows_v3")
  File "/migration_service/data/postgres_async_db.py", line 10, in is_present
    with (await AsyncPostgresDB.get_instance().pool.cursor()) as cur:
AttributeError: 'NoneType' object has no attribute 'cursor'
/bin/sh: 1: metadata_service: not found
```

The password should be escaped when [setting up the DSN](https://github.com/Netflix/metaflow-service/blob/master/services/data/postgres_async_db.py#L59), otherwise the service can fail to start, resulting in a Metaflow stack that does not work.

**Comment by oavdeev** [comment]
Similar issue with the migration service if you happen to have a dollar sign in the generated password ( [thread on gitter](https://gitter.im/metaflow_org/community?at=6074b397b9e6de24d62f36f5) ). Migration service does [some escaping](https://github.com/Netflix/metaflow-service/blob/master/services/migration_service/migration_config.py#L3) but it is not sufficient. Should probably just use `shlex.quote(..)` instead there.

**Comment by valayDave** [comment]
Escaping special characters in password will also be required for the [Goose template](https://github.com/Netflix/metaflow-service/blob/master/services/migration_service/api/__init__.py#L12) ; I can have a jab at this issue;

**Comment by valayDave** [comment]
We can close this now.
