### ISSUE TITLE
"goose: not found" in migrations service when running separately from metadata service

### ISSUE THREAD

**Issue by LHCGreg** [Netflix/metaflow-service#24]
I am trying to get the metadata service and migrations service set up as separate services. I built two separate images using `Dockerfile.metadata_service` and `Dockerfile.migration_service` on the 2.0.3 git tag. On doing a GET of /db_schema_status of the migrations service, I get

```
{"detail": "Exception('unable to get db version via goose: /bin/sh: 1: goose: not found\\n')"}
```

A cursory examination of the three dockerfiles (including the one that combines the two services) shows that the combined dockerfile installs goose but the individual dockerfiles do not. I also noticed libpq-dev in the combined dockerfile but not in the individual ones.

**Comment by ferras** [comment]
hey @LHCGreg thanks for bringing this up. The individual docker files are mostly meant for development purposes and not used as part of our prod deployment (publishing image to dockerhub). But I agree it does make sense to update Dockerfile.migration_service to include goose

**Comment by oavdeev** [comment]
the way we use goose changed quite a bit since this, closing the issue
