### ISSUE TITLE
Integrating with metaflow runs

### ISSUE THREAD

**Issue by jaysonpryde** [Netflix/metaflow-service#3]
How do I configure/integrate metaflow to this metadata service? Either locally or deploy when deployed in aws? 

Based on metaflow configure's usage, I can't see anything related to configuring just the metadata service:

<img width="757" alt="Screen Shot 2020-01-11 at 10 40 44 AM" src="https://user-images.githubusercontent.com/4818451/72197670-db5b8600-345e-11ea-8954-984e3c45ce55.png">

**Comment by jaysonpryde** [comment]
nevermind this. I was able to connect to the aws RDS instance

**Comment by romain-intel** [comment]
Glad you got it working. Let us know if you face other issues. Thanks!
