### ISSUE TITLE
Schema "public" hardcode in postgres_async_db.py

### ISSUE THREAD

**Issue by alcaldj** [Netflix/metaflow-service#335]
Although the function setup_trigger_notify allow you to pass postgresql schema as a parameter, the line where it is invoked (line 164 on same file), schema parameter is not passed. I would suggest to create it an env variable and pass it. If variable is empty, then public schema in postrges would be used.

I installed Metaflow service on a custom schema but when i tried to start Metaflow UI, it was failing because tables were not on PUBLIC schema. I implemented the proposed solution and it did work.

Thanks a lot for your support in advance and great job!!

**Comment by saikonen** [comment]
this should nowadays be configurable with the `DB_SCHEMA_NAME` env var.
