### ISSUE TITLE
Move on from Python 3.7 before security updates are discontinued. 

### ISSUE THREAD

**Issue by saikonen** [Netflix/metaflow-service#352]
The main way that the services are released is through the published docker image. This, along with all of the service codebase is currently running and tested on Python 3.7, which is scheduled for EOL the coming summer (https://devguide.python.org/versions/).

As we do not have any backward compatibility requirements for the execution of the codebase due to the way it is released, it could be considered that we move to a more recent version of Python, along with updating the base image for the docker build.

**Comment by dhpollack** [comment]
How many times can I upvote this?

**Comment by saikonen** [comment]
Addressed in release [v2.4.2](https://github.com/Netflix/metaflow-service/releases/tag/v2.4.2)
